# Generated by Django 5.2.7 on 2025-10-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Edu.exercise')),
            ],
        ),
    ]
