# Generated by Django 5.2.7 on 2025-10-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conTests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
